config.codigo=10200
config.usuario=juan
config.mensaje=Bienvenido a Spring César
config.listOfValue=saludos, bienvenidos, al año 2026
config.listaValor=Enero,Febrero,Marzo,Abril
config.valorMap={nombre: 'Juan', apellido:'Perez', curso:'primero', year:'2026'}
config.dni=100200